<a href="https://colab.research.google.com/github/demsaid400-cpu/DI_BOOTCAMP/blob/main/ExercicesXP_1_to_10_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')

rows_before = len(titanic)

duplicates = titanic.duplicated()

num_duplicates = duplicates.sum()

print("Nombre de doublons trouvés :", num_duplicates)

titanic_clean = titanic.drop_duplicates()

rows_after = len(titanic_clean)

print("Nombre de lignes avant suppression :", rows_before)
print("Nombre de lignes après suppression :", rows_after)
print("Nombre de lignes supprimées :", rows_before - rows_after)

print("Doublons restants :", titanic_clean.duplicated().sum())
print("\nInformations sur le dataset nettoyé :")
print(titanic_clean.info())

print("\nPremières lignes du dataset nettoyé :")
print(titanic_clean.head())

Nombre de doublons trouvés : 107
Nombre de lignes avant suppression : 891
Nombre de lignes après suppression : 784
Nombre de lignes supprimées : 107
Doublons restants : 0

Informations sur le dataset nettoyé :
<class 'pandas.core.frame.DataFrame'>
Index: 784 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     784 non-null    int64
 1   pclass       784 non-null    int64
 2   sex          784 non-null    object
 3   age          678 non-null    float64
 4   sibsp        784 non-null    int64
 5   parch        784 non-null    int64
 6   fare         784 non-null    float64
 7   embarked     782 non-null    object
 8   class        784 non-null    category
 9   who          784 non-null    object
 10  adult_male   784 non-null    bool
 11  deck         202 non-null    category
 12  embark_town  782 non-null    object
 13  alive        784 non-null    object
 14  alone        784 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 77.0+ KB
None

Premières lignes du dataset nettoyé :
   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

In [ ]:
import pandas as pd
import seaborn as sns
from sklearn.impute import SimpleImputer

titanic = sns.load_dataset('titanic')

print(titanic.head())

titanic_dropna = titanic.dropna()

print("Dimensions avant suppression :", titanic.shape)
print("Dimensions après suppression :", titanic_dropna.shape)

titanic_mean = titanic.copy()

titanic_mean['age'] = titanic_mean['age'].fillna(
    titanic_mean['age'].mean()
)

print("Valeurs manquantes dans age :")
print(titanic_mean['age'].isnull().sum())

titanic_imputer = titanic.copy()

imputer = SimpleImputer(strategy='median')

titanic_imputer[['age']] = imputer.fit_transform(
    titanic_imputer[['age']]
)

print("Valeurs manquantes dans age :")
print(titanic_imputer['age'].isnull().sum())

titanic_constant = titanic.copy()

titanic_constant['deck'] = titanic_constant['deck'].cat.add_categories('Unknown')
titanic_constant['deck'] = titanic_constant['deck'].fillna('Unknown')

titanic_constant['embark_town'] = titanic_constant['embark_town'].fillna('Unknown')

print(titanic_constant[['deck', 'embark_town']].isnull().sum())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True
Dimensions avant suppression : (891, 15)
Dimensions après suppression : (182, 15)
Valeurs manquantes dans age :
0
Valeurs manquantes dans age :
0
deck           0
embark_town    0
dtype: int64

In [ ]:
print("Valeurs manquantes après traitement :\n")

print("Dataset avec moyenne :")
print(titanic_mean.isnull().sum())

print("\nDataset avec constante :")
print(titanic_constant.isnull().sum())

Valeurs manquantes après traitement :

Dataset avec moyenne :
survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

Dataset avec constante :
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck             0
embark_town      0
alive            0
alone            0
dtype: int64

In [10]:
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

titanic = sns.load_dataset('titanic')

print("Colonnes disponibles :", titanic.columns.tolist())

titanic['family_size'] = titanic['sibsp'] + titanic['parch'] + 1

print("\nAperçu des colonnes de famille :")
display(titanic[['sibsp', 'parch', 'family_size']].head())

Colonnes disponibles : ['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']

Aperçu des colonnes de famille :

   sibsp  parch  family_size
0      1      0            2
1      1      0            2
2      0      0            1
3      1      0            2
4      0      0            1

In [16]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

titanic['person_type'] = titanic['who'].replace({
    'man': 'Adult Male',
    'woman': 'Adult Female',
    'child': 'Minor'
})

print("Répartition des types de personnes :")
print(titanic['person_type'].value_counts())

le = LabelEncoder()
titanic['type_encoded'] = le.fit_transform(titanic['person_type'])

print("\nAperçu de l'encodage :")
display(titanic[['person_type', 'type_encoded']].drop_duplicates())

Répartition des types de personnes :
person_type
Adult Male      537
Adult Female    271
Minor            83
Name: count, dtype: int64

Aperçu de l'encodage :

    person_type  type_encoded
0    Adult Male             1
1  Adult Female             0
7         Minor             2

In [18]:
titanic_encoded = pd.get_dummies(
    titanic,
    columns=['sex', 'embarked'],
    drop_first=True
)

titanic_encoded.head()
print("Colonnes ajoutées :")
print(['family_size', 'title', 'title_encoded'])

print("\nAperçu final du dataset :")
print(titanic_encoded.head())

Colonnes ajoutées :
['family_size', 'title', 'title_encoded']

Aperçu final du dataset :
   survived  pclass   age  sibsp  parch     fare  class    who  adult_male  \
0         0       3  22.0      1      0   7.2500  Third    man        True
1         1       1  38.0      1      0  71.2833  First  woman       False
2         1       3  26.0      0      0   7.9250  Third  woman       False
3         1       1  35.0      1      0  53.1000  First  woman       False
4         0       3  35.0      0      0   8.0500  Third    man        True

  deck  embark_town alive  alone  family_size   person_type  type_encoded  \
0  NaN  Southampton    no  False            2    Adult Male             1
1    C    Cherbourg   yes  False            2  Adult Female             0
2  NaN  Southampton   yes   True            1  Adult Female             0
3    C  Southampton   yes  False            2  Adult Female             0
4  NaN  Southampton    no   True            1    Adult Male             1

   sex_male  embarked_Q  embarked_S
0      True       False        True
1     False       False       False
2     False       False        True
3     False       False        True
4      True       False        True